"""Add SalaryChange and constraints

Revision ID: 82d02328889d
Revises: 001_initial
Create Date: 2025-12-14 13:04:57.556903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d02328889d'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('soldier_rate', sa.Float(), nullable=False),
    sa.Column('sergeant_rate', sa.Float(), nullable=False),
    sa.Column('officer_rate', sa.Float(), nullable=False),
    sa.Column('budget_before', sa.Float(), nullable=False),
    sa.Column('budget_after', sa.Float(), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # Use batch operation to add constraint for SQLite compatibility
    with op.batch_alter_table('server_economy') as batch_op:
         batch_op.create_check_constraint('check_single_row', 'id = 1')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_history')
    # ### end Alembic commands ###
